//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Sudoku Solver.rc
//
#define IDD_SUDOKUSOLVER_DIALOG         102
#define IDD_DIALOGBAR                   103
#define IDB_BITMAP1                     137
#define IDB_BITMAP2                     138
#define IDB_BITMAP4                     143
#define IDB_ASOL2                       143
#define IDB_BITMAP5                     144
#define IDB_9M                          144
#define IDB_BITMAP6                     145
#define IDB_BITMAP3                     146
#define IDB_BITMAP7                     147
#define IDB_BITMAP8                     148
#define IDB_BITMAP10                    150
#define ID_                             151
#define IDB_BITMAP11                    152
#define IDB_SOLVE1                      152
#define IDB_SOLVE2                      153
#define IDB_BITMAP9                     156
#define IDB_BITMAP12                    157
#define IDB_BITMAP14                    160
#define IDB_BITMAP15                    161
#define IDB_BITMAP16                    162
#define IDB_BITMAP13                    165
#define IDB_BITMAP18                    168
#define IDB_BITM                        168
#define IDB_BIT                         169
#define IDB_BITMAP19                    170
#define IDB_BITMAP20                    171
#define IDB_BITMAP21                    172
#define IDB_BITMAP22                    173
#define IDB_BITMAP23                    174
#define IDB_BITMAP24                    175
#define IDB_BITMAP25                    176
#define IDB_BITMAP17                    177
#define IDB_BITMAP27                    179
#define IDB_BITMAP28                    180
#define IDB_ABT22                       183
#define IDB_ABT221                      183
#define IDB_Ajanth                      183
#define IDB_ABT1                        184
#define IDB_ABOUT2                      185
#define IDB_ABOUT1                      186
#define IDB_DIF1                        191
#define IDB_MOD2                        192
#define IDB_EASY2                       193
#define IDB_MOD1                        194
#define IDB_DIF2                        195
#define IDB_EASY1                       196
#define IDB_ASOL1                       198
#define IDB_BITMAP26                    199
#define IDB_BITMAP29                    200
#define IDC_CURSOR1                     206
#define IDI_ICON1                       222
#define IDB_CANCEL1                     224
#define IDB_CANCEL2                     225
#define IDB_BACKTRACK1                  226
#define IDB_BACKTRACK2                  227
#define IDB_BITMAP30                    228
#define IDB_2                           228
#define IDB_BITMAP31                    229
#define IDB_2M                          229
#define IDB_1M                          230
#define IDB_1                           231
#define IDB_BITMAP34                    232
#define IDB_3                           232
#define IDB_BITMAP35                    233
#define IDB_3M                          233
#define IDB_BITMAP36                    234
#define IDB_4                           234
#define IDB_BITMAP37                    235
#define IDB_4M                          235
#define IDB_BITMAP38                    236
#define IDB_5M                          236
#define IDB_BITMAP39                    237
#define IDB_5                           237
#define IDB_BITMAP40                    238
#define IDB_6                           238
#define IDB_BITMAP41                    239
#define IDB_6M                          239
#define IDB_BITMAP42                    240
#define IDB_7                           240
#define IDB_BITMAP43                    241
#define IDB_7M                          241
#define IDB_BITMAP44                    242
#define IDB_8                           242
#define IDB_BITMAP45                    243
#define IDB_8M                          243
#define IDB_BITMAP46                    244
#define IDB_9                           244
#define IDB_BITMAP47                    245
#define IDB_BITMAP32                    248
#define IDB_SAVEM                       250
#define IDB_SAVE                        254
#define IDR_WAVE1                       255
#define IDR_WAVE2                       256
#define IDB_ABOUT                       258
#define IDB_MUS2                        259
#define IDB_MUS1                        260
#define IDB_CLEAR1                      261
#define IDB_BITMAP48                    262
#define IDB_CLEAR2                      262
#define IDC_PREV                        1000
#define IDC_NXT                         1001
#define IDC_EDIT1                       1002
#define IDC_EDIT2                       1003
#define IDMIN                           1003
#define IDC_EDIT3                       1004
#define IDC_BUTTON1                     1004
#define IDC_EDIT4                       1005
#define IDC_BUTTON2                     1005
#define IDC_EDIT5                       1006
#define IDC_BUTTON3                     1006
#define IDC_EDIT6                       1007
#define IDC_EDIT7                       1008
#define IDC_MOD                         1008
#define IDC_EDIT8                       1009
#define IDC_EASY                        1009
#define IDC_EDIT9                       1010
#define IDC_DIFF                        1010
#define IDC_EDIT10                      1011
#define IDC_BUTTON7                     1011
#define IDC_ASOL                        1011
#define IDC_TIME                        1012
#define IDC_CANCER                      1014
#define IDC_TIME2                       1015
#define IDC_TIME3                       1016
#define IDC_UNDO1                       1018
#define IDC_SAVE                        1024
#define IDC_BUTTON13                    1025
#define IDC_PIC                         1025
#define IDC_MUSIC                       1026
#define IDC_CLEAR                       1027
#define IDC_BUTTON14                    1031
#define IDC_BUTTON15                    1032
#define IDC_BUTTON16                    1033
#define IDC_BUTTON17                    1034
#define IDC_BUTTON18                    1035
#define IDC_BUTTON19                    1036
#define IDC_BUTTON20                    1037
#define IDC_BUTTON21                    1038
#define ID_1_2                          32771
#define ID_1_3                          32772
#define ID_1_4                          32773
#define ID_1_5                          32774
#define ID_1_6                          32775
#define ID_1_7                          32776
#define ID_1_8                          32777
#define ID_1_9                          32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        263
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
